#!/usr/bin/env node

var Game = require('./dist/server/Game.js').default;
var Client = require('./dist/client/Client.js').default;

var game = new Game();
var client = new Client();

client.execute(game);
